### PR TITLE
Improve error handling for team fetching

### PR DESCRIPTION
**Pull request by danielkza**

### CODE REVIEW

**Comment by patrobinson** [comment]
Hi @danielkza sorry for not replying for some reason I was not "watching" my own repository!

This change is no longer valid as we now set [autopaginate always](https://github.com/patrobinson/linux-hub/blob/8b919b4f143fd96ec02127c25f94e394a4808f79/lib/linux-hub/cli.rb#L9), since it's useful in other places too.

**Comment by danielkza** [comment]
@patrobinson Sure. What about the nil-check for `team`?

**Comment by patrobinson** [comment]
@danielkza Yep that's a great check to have. Feel free to push any commits to this PR and I'll re-open or just open a new PR

**Comment by danielkza** [comment]
@patrobinson Rebased and updated. edit: github isn't updating for some weird reason, I'll check it. edit2: maybe the commits don't update when the PR is closed, but my branch is as I expected it to be.

**Pull request closed without merging**
